Add direct tool access. (#1)

diff --git a/toolchains/tool_wrappers/x86_64/linux/arm-none-eabi/12.3.rel1/arm-none-eabi-strip b/toolchains/tool_wrappers/x86_64/linux/arm-none-eabi/12.3.rel1/arm-none-eabi-strip
--- a/toolchains/tool_wrappers/x86_64/linux/arm-none-eabi/12.3.rel1/arm-none-eabi-strip
+++ b/toolchains/tool_wrappers/x86_64/linux/arm-none-eabi/12.3.rel1/arm-none-eabi-strip
@@ -1,2 +1,23 @@
 #!/bin/bash
-exec external/arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-strip $@
+
+TOOL_PATH=arm-gnu-toolchain-12.3.rel1-x86_64-arm-none-eabi/bin/arm-none-eabi-strip
+
+# First check if we can find the executable directly and then revert to runfiles.
+# This is necessary because when used in the toolchain, the runfiles library is not available.
+if [[ -f external/${TOOL_PATH} ]]; then
+  exec external/${TOOL_PATH} $@
+fi
+
+# --- begin runfiles.bash initialization v3 ---
+# Copy-pasted from the Bazel Bash runfiles library v3.
+set -uo pipefail; set +e; f=bazel_tools/tools/bash/runfiles/runfiles.bash
+source "${RUNFILES_DIR:-/dev/null}/$f" 2>/dev/null || \
+  source "$(grep -sm1 "^$f " "${RUNFILES_MANIFEST_FILE:-/dev/null}" | cut -f2- -d' ')" 2>/dev/null || \
+  source "$0.runfiles/$f" 2>/dev/null || \
+  source "$(grep -sm1 "^$f " "$0.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
+  source "$(grep -sm1 "^$f " "$0.exe.runfiles_manifest" | cut -f2- -d' ')" 2>/dev/null || \
+  { echo>&2 "ERROR: cannot find $f"; exit 1; }; f=; set -e
+# --- end runfiles.bash initialization v3 ---
+
+exec $(rlocation ${TOOL_PATH}) $@
+')
